export const INITIAL_FETCH = 'INITIAL_FETCH';
export const INSTA_VINE_POSTS = 'INSTA_VINE_POSTS';
export const TWITTER_POSTS = 'TWITTER_POSTS';
export const MAIN_DISPLAYED = 'MAIN_DISPLAYED';
export const SIDEBAR_DISPLAYED = 'SIDEBAR_DISPLAYED';
export const AVATAR_VISIBILITY = 'AVATAR_VISIBILITY';
